### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mvantellingen** [labd/node-federated-token#1]
After discussion with @MichielBijland we came to the following roadmap for the federated-token package.

 - [ ] Support key rotation in the JWT by using the `kid` field.
 - [ ] Add support to use KMS (AWS and GCP) as encryption and verification service (could be a separate signer class)
 - [ ] Verify issuer and audience values
